find_path(Bezitopo_INCLUDE_DIR bezitopo.h)
find_library(Bezitopo_LIBRARY NAMES bezitopo)
if (Bezitopo_INCLUDE_DIR AND Bezitopo_LIBRARY)
  set(Bezitopo_FOUND TRUE)
endif ()

if (Bezitopo_FOUND)
  if (NOT Bezitopo_FIND_QUIETLY)
    message(STATUS "Found Bezitopo: ${Bezitopo_LIBRARY}")
  endif ()
else ()
  if (Bezitopo_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find Bezitopo")
  endif ()
endif ()
